### ISSUE TITLE
Can't build firmware due to cryptoauthlib changes

### ISSUE THREAD

**Issue by CarlMitchellKT** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#15]
The required version of cryptoauthlib (commit b31ed52daf) is not api-compatible with the current version. Ideally this project would be updated to use the new version of cryptoauthlib, and if not instructions for using the correct commit should be added to the firmware readme.md.

**Comment by BenUdall-Microchip** [comment]
Hello commit e3e76b2 updated the project to use the latest CryptoAuthLib release.
