### ISSUE TITLE
cert2certdef.py does not work with serial numbers prefixed with 00

### ISSUE THREAD

**Issue by sandeepmistry** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#3]
The serial number for my certificate which was signed by AWS IoT is:

`F8:3A:AC:49:2E:E7:52:F2:83:8C:60:F3:C2:AA:6A:BF:9E:2A:CD:DD`

However, in the .pem file it is stored as `00:F8:3A:AC:49:2E:E7:52:F2:83:8C:60:F3:C2:AA:6A:BF:9E:2A:CD:DD` - the length is 21 instead of 20. I think the extra 00 prefix byte was adding to the serial number because it starts with 0xf8 which is a negative number.

**Comment by BenUdall-Microchip** [comment]
The cert2certdef.py script wasn't written to handle arbitrary certificates, but is pretty narrowly focused on the certificate formats the included scripts generate, it will accommodate simple name changes, but beyond that is risky.

The certificate definition format that the firmware uses requires that the serial number always be the same size. You'll notice the random_cert_sn() and device_cert_sn() functions in aws_kit_common.py intentionally construct certificate serial numbers that won't change size when encoded in ASN.1 DER (most significant bits are forced to 01).
