### ISSUE TITLE
SAMG55 firmware update Build errors

### ISSUE THREAD

**Issue by ronnytittoto** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#9]
Building the firmware AWS_IoT_Zero_Touch_SAMG55.atsln project with Ateml Studio 7 fails with some errors.
e.g. atcacert/atcacert_client.h: No such file or directory	

CryptoAuthLib missing?

**Comment by BenUdall-Microchip** [comment]
Hello,
CryptoAuthLib is included as a git submodule, which requires a slight modification of the git commands to clone everything.

If you already have the repository cloned, then the following command will pull the CryptoAuthLib submodule:
`git submodule update --init`

If you want to clone everything from scratch, you can use this command to grab submodules as well:
`git clone --recurse-submodules https://github.com/MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit.git`

To do it manually (downloading zip archives), you can go to the parent folder of CryptoAuthLib [firmware/SAMG55/AWS_IoT_Zero_Touch_SAMG55/src](https://github.com/MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit/tree/master/firmware/SAMG55/AWS_IoT_Zero_Touch_SAMG55/src) and click on the CryptoAuthLib link to go to the proper commit. From there, you can download CryptoAuthLib and extract it into that folder.

**Comment by ronnytittoto** [comment]
Great! Thanks for clarifying!
